# Generated by Django 5.1.3 on 2024-11-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
