# Generated by Django 5.1.3 on 2024-11-14 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_investments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calls',
            name='user',
        ),
    ]
