# Generated by Django 5.1.3 on 2024-11-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_calls_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investments',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='investments',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
