# Generated by Django 5.1.3 on 2024-11-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_investments_price_alter_investments_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='calls',
            name='price_of_acre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calls',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investments',
            name='size',
            field=models.IntegerField(),
        ),
    ]
