# Generated by Django 5.1.3 on 2024-11-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_calls_price_of_acre_calls_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investments',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investments',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
