# Generated by Django 5.1.3 on 2024-11-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_investments_price_alter_investments_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='investments',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
