# Generated by Django 5.1.3 on 2024-11-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_investments_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='calls',
            name='projected_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calls',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
