# Generated by Django 5.1.3 on 2024-11-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_calls_projected_end_date_calls_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='investments',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
