# Generated by Django 5.1.3 on 2024-11-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_investments_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='legal_name',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
        migrations.AddField(
            model_name='investments',
            name='full_name',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
